import {
  Activity,
  ArrowUpRight,
  Baby,
  Ban,
  Banknote,
  BarChart3,
  Beer,
  Bike,
  Book,
  Briefcase,
  Building2,
  Bus,
  CalendarSync,
  Camera,
  Car,
  CircleDollarSign,
  CircleEllipsis,
  CircleUser,
  Coffee,
  Coins,
  CreditCard,
  Cross,
  Droplet,
  Dumbbell,
  FileText,
  Film,
  Flame,
  Footprints,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HandCoins,
  Headphones,
  Heart,
  House,
  Key,
  Landmark,
  Laptop,
  Leaf,
  MapPin,
  Music,
  Newspaper,
  Package,
  PawPrint,
  PenLine,
  Phone,
  PieChart,
  PiggyBank,
  Pill,
  Plane,
  Printer,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Sparkles,
  Store,
  Tag,
  Ticket,
  TrendingUp,
  TvMinimalPlay,
  Umbrella,
  Undo2,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";
import { cloneElement } from "react";

const iconsMapping = {
  'dollarsign.circle.fill': <CircleDollarSign />,
  'ellipsis.circle.fill': <CircleEllipsis />,
  'heart.fill': <Heart />,
  'cart.fill': <ShoppingCart />,
  'dollarsign.arrow.circlepath': <CalendarSync />,
  'creditcard.circle.fill': <CreditCard />,
  'wrench.and.screwdriver.fill': <Wrench />,
  'newspaper.fill': <Newspaper />,
  'basket.fill': <ShoppingBasket />,
  'checkmark.shield.fill': <ShieldCheck />,
  'square.and.arrow.down.fill': <HandCoins />,
  'airplane.circle.fill': <Plane />,
  'fork.knife.circle.fill': <Utensils />,
  'play.tv.fill': <TvMinimalPlay />,
  'gift.fill': <Gift />,
  'house.fill': <House />,
  'car.fill': <Car />,
  'book.fill': <Book />,
  'bag.fill': <ShoppingBag />,
  'cup.and.saucer.fill': <Coffee />,
  'pawprint.fill': <PawPrint />,
  'figure.run': <Activity />,
  'phone.fill': <Phone />,
  'bolt.fill': <Zap />,
  'graduationcap.fill': <GraduationCap />,
  'briefcase.fill': <Briefcase />,
  'banknote.fill': <Banknote />,
  'chart.line.uptrend.xyaxis': <TrendingUp />,
  'fuelpump.fill': <Fuel />,
  'bus.fill': <Bus />,
  'gamecontroller.fill': <Gamepad2 />,
  'music.note': <Music />,
  'film.fill': <Film />,
  'camera.fill': <Camera />,
  'hammer.fill': <Hammer />,
  'leaf.fill': <Leaf />,
  'cross.case.fill': <Cross />,
  'pill.fill': <Pill />,
  'tshirt.fill': <Shirt />,
  'building.2.fill': <Building2 />,
  'wifi': <Wifi />,
  'drop.fill': <Droplet />,
  'flame.fill': <Flame />,
  'dumbbell.fill': <Dumbbell />,
  'bicycle': <Bike />,
  'ticket.fill': <Ticket />,
  'figure.child': <Baby />,
  'person.2.fill': <Users />,
  'scissors': <Scissors />,
  'headphones': <Headphones />,
  'printer.fill': <Printer />,
  'wineglass.fill': <Wine />,
  'shippingbox.fill': <Package />,
  'takeoutbag.and.cup.and.straw.fill': <Beer />,
  'beach.umbrella.fill': <Umbrella />,
  'mappin.circle.fill': <MapPin />,
  'figure.walk': <Footprints />,
  'sparkles': <Sparkles />,
  'doc.text.fill': <FileText />,
  'tag.fill': <Tag />,
  'key.fill': <Key />,
  'building.columns.fill': <Landmark />,
  'chart.bar.fill': <BarChart3 />,
  'laptopcomputer': <Laptop />,
  'storefront.fill': <Store />,
  'tray.full.fill': <PiggyBank />,
  'arrow.uturn.backward.circle.fill': <Undo2 />,
  'pencil.and.scribble': <PenLine />,
  'person.crop.circle.fill': <CircleUser />,
  'wallet.pass.fill': <Wallet />,
  'centsign.circle.fill': <Coins />,
  'chart.pie.fill': <PieChart />,
  'arrow.up.right.circle.fill': <ArrowUpRight />,
} as const;

export type IconName = keyof typeof iconsMapping | string;

interface ComponentProps {
  name: IconName;
  size?: number
}

export function Icon({name, size = 24}: ComponentProps) {
  const IconComponent = iconsMapping[name as keyof typeof iconsMapping];
  if (!IconComponent) {
    return (
      <Ban size={size} />
    )
  }
  return cloneElement(IconComponent, { size });
}
